pull_request_rules:
  - name: approve generated data updates
    conditions:
      - head=automation/nuget-update
    actions:
      review:
        type: APPROVE
        message: Automatically approving generated data update.

  - name: merge dependabot updates
    conditions:
      - author=dependabot[bot]
      - check-success=validate
    actions:
      review:
        type: APPROVE
        message: Automatically approving Dependabot update.
      merge:
        method: squash
