name: nuget
on:
  workflow_dispatch:
    inputs:
      timeout:
        type: number
        description: Timeout in minutes
        required: false
        default: 360

  schedule:
    - cron: "0 2 1 * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  nuget:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(github.event.inputs.timeout || '360') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate nuget data
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet tool update -g dotnet-sponsor
          sponsor nuget --tos --exceptions --force

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: automation/nuget-update
          delete-branch: true
          commit-message: Update generated NuGet data
          title: Update generated NuGet data
          body: Automated refresh of generated NuGet data.
          add-paths: |
            *.json
